const SEATING_CAPACITY=10
const WAITING_CAPACITY=5
const BARTENDER_CAPACITY=1000
const EVENTS_DIR='events'

module.exports = {
  SEATING_CAPACITY,
  WAITING_CAPACITY,
  BARTENDER_CAPACITY,
  EVENTS_DIR
}