const SEATING_CAPACITY=10
const WAITING_CAPACITY=10
const EVENTS_DIR='app/model/events'
const CUSTOMER_DRINKS_MIN = 1
const CUSTOMER_DRINKS_MAX = 5
const CUSTOMER_DRINK_TIME_MIN=100 // 100
const CUSTOMER_DRINK_TIME_MAX=500 // 500
const CUSTOMER_ARRIVAL_TIME_MIN=1 // 50
const CUSTOMER_ARRIVAL_TIME_MAX=50 // 100
const BAR_TIME=20
const PER_HOUR_IN_MS=1000

module.exports = {
  SEATING_CAPACITY,
  WAITING_CAPACITY,
  EVENTS_DIR,
  CUSTOMER_DRINKS_MIN,
  CUSTOMER_DRINKS_MAX,
  CUSTOMER_DRINK_TIME_MIN,
  CUSTOMER_DRINK_TIME_MAX,
  CUSTOMER_ARRIVAL_TIME_MIN,
  CUSTOMER_ARRIVAL_TIME_MAX,
  BAR_TIME,
  PER_HOUR_IN_MS
}